### ISSUE TITLE
bug in vgpCCM.py

### ISSUE THREAD

**Issue by Kkkkrypton123** [lemiceterieux/gpCCM#1]
the variable posteriormu in GP.forward function has not been defined before, do you mean mu?

**Comment by lemiceterieux** [comment]
Hi! Thanks for this comment. Actually, to calculate entropy of the posterior Gaussian distribution we shouldn't need mu, so this is a relic of old code and could be safely removed. Anyway, I need to organize how to integrate this older code with my newer code that can also explore "context-dependent"  coupling (see: https://github.com/lemiceterieux/PPI-GP-CrossMapping). And I'm also exploring how to update this code to a Jax codebase to make it faster. In the meantime, I'd suggest you use this code here: https://github.com/lemiceterieux/PPI-GP-CrossMapping/blob/main/HaxbyPPI-CCM/vgpccmbatch.py. If you don't care about "context dependent" effects, just set the variable "Mu" to a zero array the same size as X.

**Comment by Kkkkrypton123** [comment]
thank you fpr your help. By the way ,the function which named batch_distance can‘t found in your code .Could you tell me how to get it?

**Comment by lemiceterieux** [comment]
Batch distance was just computing a distance matrix. I should replace that with torch.cdist (as I did in function "squaredExpKernelARD"). In my papers I published, that's the  kernel I utilized, anyway.

**Comment by Kkkkrypton123** [comment]
thank you. that's useful.
